[package]
name = "pokemon_trainer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rouille = "3.2.1"
serde = {version = "1.0.130", features = ["derive"]}
serde_json = "1.0.67"

rdkafka = { version = "0.28", features=["cmake-build"]}
async-trait = "0.1.57"
